services:
  # 后端服务
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:4001:4001"
    volumes:
      - ./server/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=4001
    restart: unless-stopped

  # 前端服务
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:4000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  dish_data:
